services:
    _defaults:
        autoconfigure: true

    Terminal42\WebpackEncoreBundle\EventListener\EntrypointOptionsListener:
        arguments:
            - '%terminal42_webpack_encore.output_path%'

    Terminal42\WebpackEncoreBundle\EventListener\GeneratePageListener:
        arguments:
            - '@webpack_encore.twig_entry_files_extension'

    Terminal42\WebpackEncoreBundle\EventListener\TemplateHelperListener:
        arguments:
            - '@webpack_encore.twig_entry_files_extension'

    Terminal42\WebpackEncoreBundle\EventListener\InsertTagsListener:
        arguments:
            - '@webpack_encore.twig_entry_files_extension'
